version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-dapr-sample
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: "host.docker.internal"
      DATABASE_PORT: 5432
      DATABASE_NAME: "node-dapr-sample"
      DATABASE_USERNAME: "postgres"
      DATABASE_PASSWORD: "postgres"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network
    command: npm run start:dev

networks:
  app-network:
    driver: bridge