version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: master
      POSTGRES_DB: node-dapr-sample
    ports:
      - "5432:5432"
    networks:
      - my-network

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: master
      DATABASE_NAME: node-dapr-sample
    ports:
      - "3000:3000"
    networks:
      - my-network

  app-dapr:
    image: "daprio/daprd:latest"
    command: [
      "./daprd",
      "-app-id", "app",
      "-app-port", "3000",
      "-placement-host-address", "placement:50006",
      "-dapr-http-port", "3500",
      "-components-path", "/components"
    ]
    volumes:
      - "./src/dapr/components:/components"
    depends_on:
      - app
    network_mode: "service:app"

  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
