apiVersion: apps/v1
kind: Deployment
metadata:
  name: ns-main-service
  labels:
    app: ns-main-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ns-main-service
  template:
    metadata:
      labels:
        app: ns-main-service
    spec:
      containers:
        - name: ns-main-service
          image: local/ns-main-service:latest
          imagePullPolicy: IfNotPresent   # Prevents pulling from remote if image exists locally
          ports:
            - containerPort: 3000
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-main-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-main-credentials
                  key: password
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-main-credentials
                  key: url
