apiVersion: v1
kind: Secret
metadata:
  name: db-main-credentials
type: Opaque
data:
  username: "cG9zdGdyZXM="
  password: "bWFzdGVy"
  url: "cG9zdGdyZXNxbDovL3Bvc3RncmVzOm1hc3RlckBwb3N0Z3JlLW1haW46NTQzMi9ucy1tYWluP3NjaGVtYT1wdWJsaWM="