version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: master
      POSTGRES_DB: node-dapr-sample
    ports:
      - "5434:5432"
    networks:
      - my-network

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:master@db:5432/node-dapr-sample?schema=public"
      NEXT_PUBLIC_CONTRACT_API_URL: ${NEXT_PUBLIC_CONTRACT_API_URL}
      NEXT_PUBLIC_CLIENT_API_URL: ${NEXT_PUBLIC_CLIENT_API_URL}
    ports:
      - "3001:3000"
    networks:
      - my-network

  test-db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: node-dapr-test
    ports:
      - "5435:5432"
    networks:
      - my-network

  test-app:
    build: .
    depends_on:
      - test-db
    environment:
      DATABASE_URL: "postgresql://postgres:testpass@test-db:5432/node-dapr-test?schema=public"
      NEXT_PUBLIC_CONTRACT_API_URL: ${NEXT_PUBLIC_CONTRACT_API_URL}
    networks:
      - my-network
    command: ["npm", "run", "test"]
networks:
  my-network:
    driver: bridge